# Is the FIFA World Cup Draw Truely Random?

In [1]:
#Here we import the libraries we will be using for this project.

import pandas as pd
import numpy as np
import math
import seaborn as sns
import pandas as pd

from scipy import stats
from matplotlib import pyplot as plt

%matplotlib inline

In [2]:
#Here we load the data set and store in the variable covid_19_EI
#We use the pandas library to read the data set
fifaRanks = pd.read_csv("fifa_ranking.csv")

##  1 Undestanding the data

In [3]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.20.3
Pandas:  1.2.4

In [4]:
fifaRanks

,rank,country_full,country_abrv,total_points,previous_points,rank_change,cur_year_avg,cur_year_avg_weighted,last_year_avg,last_year_avg_weighted,two_year_ago_avg,two_year_ago_weighted,three_year_ago_avg,three_year_ago_weighted,confederation,rank_date
0,1,Germany,GER,0.0,57,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,1993-08-08
1,2,Italy,ITA,0.0,57,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,1993-08-08
2,3,Switzerland,SUI,0.0,50,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,1993-08-08
3,4,Sweden,SWE,0.0,55,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,1993-08-08
4,5,Argentina,ARG,0.0,51,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CONMEBOL,1993-08-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57788,206,Anguilla,AIA,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CONCACAF,2018-06-07
57789,206,Bahamas,BAH,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CONCACAF,2018-06-07
57790,206,Eritrea,ERI,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CAF,2018-06-07
57791,206,Somalia,SOM,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CAF,2018-06-07
57792,206,Tonga,TGA,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OFC,2018-06-07

In [5]:
fifaFeatures = fifaRanks.drop(['cur_year_avg','cur_year_avg_weighted','last_year_avg','last_year_avg_weighted','two_year_ago_avg',
                   'three_year_ago_avg', 'three_year_ago_weighted'], axis = 1)

In [6]:
fifaFeatures

,rank,country_full,country_abrv,total_points,previous_points,rank_change,two_year_ago_weighted,confederation,rank_date
0,1,Germany,GER,0.0,57,0,0.0,UEFA,1993-08-08
1,2,Italy,ITA,0.0,57,0,0.0,UEFA,1993-08-08
2,3,Switzerland,SUI,0.0,50,9,0.0,UEFA,1993-08-08
3,4,Sweden,SWE,0.0,55,0,0.0,UEFA,1993-08-08
4,5,Argentina,ARG,0.0,51,5,0.0,CONMEBOL,1993-08-08
...,...,...,...,...,...,...,...,...,...
57788,206,Anguilla,AIA,0.0,0,1,0.0,CONCACAF,2018-06-07
57789,206,Bahamas,BAH,0.0,0,1,0.0,CONCACAF,2018-06-07
57790,206,Eritrea,ERI,0.0,0,1,0.0,CAF,2018-06-07
57791,206,Somalia,SOM,0.0,0,1,0.0,CAF,2018-06-07
57792,206,Tonga,TGA,0.0,0,1,0.0,OFC,2018-06-07

In [7]:
# convert date column into date format
fifaFeatures['rank_date'] = pd.to_datetime(fifaFeatures['rank_date'])
  
# filter rows on the basis of date
newdf = (fifaFeatures['rank_date'] > '8/08/1993') & (fifaFeatures['rank_date'] <= '7/06/2018')
  
# locate rows and access them using .loc() function
newdf = fifaFeatures.loc[newdf]
  
# print dataframe
print(newdf)

       rank country_full country_abrv  total_points  previous_points  \
167       1       Brazil          BRA           0.0               54
168       2        Italy          ITA           0.0               56
169       3       Norway          NOR           0.0               54
170       4      Denmark          DEN           0.0               53
171       5      England          ENG           0.0               52
...     ...          ...          ...           ...              ...
57788   206     Anguilla          AIA           0.0                0
57789   206      Bahamas          BAH           0.0                0
57790   206      Eritrea          ERI           0.0                0
57791   206      Somalia          SOM           0.0                0
57792   206        Tonga          TGA           0.0                0

       rank_change  two_year_ago_weighted confederation  rank_date
167              7                    0.0      CONMEBOL 1993-09-23
168              0                    0.0          UEFA 1993-09-23
169              6                    0.0          UEFA 1993-09-23
170              6                    0.0          UEFA 1993-09-23
171              6                    0.0          UEFA 1993-09-23
...            ...                    ...           ...        ...
57788            1                    0.0      CONCACAF 2018-06-07
57789            1                    0.0      CONCACAF 2018-06-07
57790            1                    0.0           CAF 2018-06-07
57791            1                    0.0           CAF 2018-06-07
57792            1                    0.0           OFC 2018-06-07

[57626 rows x 9 columns]

In [8]:
newdf

,rank,country_full,country_abrv,total_points,previous_points,rank_change,two_year_ago_weighted,confederation,rank_date
167,1,Brazil,BRA,0.0,54,7,0.0,CONMEBOL,1993-09-23
168,2,Italy,ITA,0.0,56,0,0.0,UEFA,1993-09-23
169,3,Norway,NOR,0.0,54,6,0.0,UEFA,1993-09-23
170,4,Denmark,DEN,0.0,53,6,0.0,UEFA,1993-09-23
171,5,England,ENG,0.0,52,6,0.0,UEFA,1993-09-23
...,...,...,...,...,...,...,...,...,...
57788,206,Anguilla,AIA,0.0,0,1,0.0,CONCACAF,2018-06-07
57789,206,Bahamas,BAH,0.0,0,1,0.0,CONCACAF,2018-06-07
57790,206,Eritrea,ERI,0.0,0,1,0.0,CAF,2018-06-07
57791,206,Somalia,SOM,0.0,0,1,0.0,CAF,2018-06-07
57792,206,Tonga,TGA,0.0,0,1,0.0,OFC,2018-06-07