In [1]:
import pandas as pd

In [2]:
df = pd.read_html('https://www.foxsports.com/soccer/fifa-world-cup/history')

In [10]:
df

[    Year                Host      Champion       Runner Up    Third Place  \
 0   2018              Russia        France         Croatia        Belgium
 1   2014              Brazil       Germany       Argentina    Netherlands
 2   2010        South Africa         Spain     Netherlands        Germany
 3   2006             Germany         Italy          France        Germany
 4   2002  South Korea, Japan        Brazil         Germany         Turkey
 5   1998              France        France          Brazil        Croatia
 6   1994       United States        Brazil           Italy         Sweden
 7   1990               Italy  West Germany       Argentina          Italy
 8   1986              Mexico     Argentina    West Germany         France
 9   1982               Spain         Italy    West Germany         Poland
 10  1978           Argentina     Argentina     Netherlands         Brazil
 11  1974        West Germany  West Germany     Netherlands         Poland
 12  1970              Mexico        Brazil           Italy   West Germany
 13  1966             England       England    West Germany       Portugal
 14  1962               Chile        Brazil  Czechoslovakia          Chile
 15  1958              Sweden        Brazil          Sweden         France
 16  1954         Switzerland  West Germany         Hungary        Austria
 17  1950              Brazil       Uruguay          Brazil         Sweden
 18  1938              France         Italy         Hungary         Brazil
 19  1934               Italy         Italy  Czechoslovakia        Germany
 20  1930             Uruguay       Uruguay       Argentina  United States

     Teams  Matches Played  Goals Scored  Avg Goals Per Game
 0      32              64           169                 2.6
 1      32              64           171                 2.7
 2      32              64           145                 2.3
 3      32              64           147                 2.3
 4      32              64           161                 2.5
 5      32              64           171                 2.7
 6      24              52           141                 2.7
 7      24              52           115                 2.2
 8      24              52           132                 2.5
 9      24              52           146                 2.8
 10     16              38           102                 2.7
 11     16              38            97                 2.6
 12     16              32            95                 3.0
 13     16              32            89                 2.8
 14     16              32            89                 2.8
 15     16              35           126                 3.6
 16     16              26           140                 5.4
 17     13              22            88                 4.0
 18     15              18            84                 4.7
 19     16              17            70                 4.1
 20     13              16            70                 3.6  ]

In [12]:
df[0]

,Year,Host,Champion,Runner Up,Third Place,Teams,Matches Played,Goals Scored,Avg Goals Per Game
0,2018,Russia,France,Croatia,Belgium,32,64,169,2.6
1,2014,Brazil,Germany,Argentina,Netherlands,32,64,171,2.7
2,2010,South Africa,Spain,Netherlands,Germany,32,64,145,2.3
3,2006,Germany,Italy,France,Germany,32,64,147,2.3
4,2002,"South Korea, Japan",Brazil,Germany,Turkey,32,64,161,2.5
5,1998,France,France,Brazil,Croatia,32,64,171,2.7
6,1994,United States,Brazil,Italy,Sweden,24,52,141,2.7
7,1990,Italy,West Germany,Argentina,Italy,24,52,115,2.2
8,1986,Mexico,Argentina,West Germany,France,24,52,132,2.5
9,1982,Spain,Italy,West Germany,Poland,24,52,146,2.8
10,1978,Argentina,Argentina,Netherlands,Brazil,16,38,102,2.7
11,1974,West Germany,West Germany,Netherlands,Poland,16,38,97,2.6
12,1970,Mexico,Brazil,Italy,West Germany,16,32,95,3.0
13,1966,England,England,West Germany,Portugal,16,32,89,2.8
14,1962,Chile,Brazil,Czechoslovakia,Chile,16,32,89,2.8
15,1958,Sweden,Brazil,Sweden,France,16,35,126,3.6
16,1954,Switzerland,West Germany,Hungary,Austria,16,26,140,5.4
17,1950,Brazil,Uruguay,Brazil,Sweden,13,22,88,4.0
18,1938,France,Italy,Hungary,Brazil,15,18,84,4.7
19,1934,Italy,Italy,Czechoslovakia,Germany,16,17,70,4.1
20,1930,Uruguay,Uruguay,Argentina,United States,13,16,70,3.6

In [16]:
df[0].dtypes

Year                    int64
Host                   object
Champion               object
Runner Up              object
Third Place            object
Teams                   int64
Matches Played          int64
Goals Scored            int64
Avg Goals Per Game    float64
dtype: object

In [19]:
# Storing the data into Pandas
# DataFrame 
data_frame = df[0]

In [ ]:
df = pd.DataFrame (products_list, columns = ['product_name'])
print (df)

In [ ]:
dataFrame = pd.DataFrame(data = data, columns = list_header)
   
# Converting Pandas DataFrame
# into CSV file
dataFrame.to_csv('Geeks.csv')

In [22]:
data_frame1 =  pd.DataFrame(data= data_frame)

In [24]:
data_frame1

,Year,Host,Champion,Runner Up,Third Place,Teams,Matches Played,Goals Scored,Avg Goals Per Game
0,2018,Russia,France,Croatia,Belgium,32,64,169,2.6
1,2014,Brazil,Germany,Argentina,Netherlands,32,64,171,2.7
2,2010,South Africa,Spain,Netherlands,Germany,32,64,145,2.3
3,2006,Germany,Italy,France,Germany,32,64,147,2.3
4,2002,"South Korea, Japan",Brazil,Germany,Turkey,32,64,161,2.5
5,1998,France,France,Brazil,Croatia,32,64,171,2.7
6,1994,United States,Brazil,Italy,Sweden,24,52,141,2.7
7,1990,Italy,West Germany,Argentina,Italy,24,52,115,2.2
8,1986,Mexico,Argentina,West Germany,France,24,52,132,2.5
9,1982,Spain,Italy,West Germany,Poland,24,52,146,2.8
10,1978,Argentina,Argentina,Netherlands,Brazil,16,38,102,2.7
11,1974,West Germany,West Germany,Netherlands,Poland,16,38,97,2.6
12,1970,Mexico,Brazil,Italy,West Germany,16,32,95,3.0
13,1966,England,England,West Germany,Portugal,16,32,89,2.8
14,1962,Chile,Brazil,Czechoslovakia,Chile,16,32,89,2.8
15,1958,Sweden,Brazil,Sweden,France,16,35,126,3.6
16,1954,Switzerland,West Germany,Hungary,Austria,16,26,140,5.4
17,1950,Brazil,Uruguay,Brazil,Sweden,13,22,88,4.0
18,1938,France,Italy,Hungary,Brazil,15,18,84,4.7
19,1934,Italy,Italy,Czechoslovakia,Germany,16,17,70,4.1
20,1930,Uruguay,Uruguay,Argentina,United States,13,16,70,3.6

In [26]:
data_frame1.to_csv('final_team_rankings.csv')